// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVjR3TrTUjXEcSqyDo5XC_-UDwTgaazPY',
    appId: '1:671810020999:web:5342dad0ba003f9d793a22',
    messagingSenderId: '671810020999',
    projectId: 'ecodataatlas',
    authDomain: 'ecodataatlas.firebaseapp.com',
    storageBucket: 'ecodataatlas.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3vVQJANMj7ERg6XIA-LJR8zZ3Vs2EQkM',
    appId: '1:671810020999:android:bea0b6f0c23941a5793a22',
    messagingSenderId: '671810020999',
    projectId: 'ecodataatlas',
    storageBucket: 'ecodataatlas.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA20Ktfs9cwWC24CKydk8IUlSkIMtABkrQ',
    appId: '1:671810020999:ios:f440ffc1db1b7e06793a22',
    messagingSenderId: '671810020999',
    projectId: 'ecodataatlas',
    storageBucket: 'ecodataatlas.firebasestorage.app',
    iosBundleId: 'com.ejseo.tempFlutterProject',
  );

}